FROM mcr.microsoft.com/dotnet/sdk:9.0 AS migrate

WORKDIR /src

COPY . .

RUN dotnet restore ./AuthService.Api.csproj
RUN dotnet tool install --global dotnet-ef --version 7.0.0

ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "AuthService.Api.csproj"]