services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  migrate:
    image: ghcr.io/${GITHUB_USERNAME}/authservice-migrate:latest
    build:
      context: .
      dockerfile: Dockerfile.migrate
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_PAT: ${GITHUB_PAT}
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: ${CONNECTIONSTRINGS__DEFAULTCONNECTION}

  api:
    image: ghcr.io/${GITHUB_USERNAME}/authservice-api:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_PAT: ${GITHUB_PAT}
    depends_on:
      - db
      - migrate
    environment:
      ConnectionStrings__DefaultConnection: ${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      KafkaSettings__BootstrapServers: ${KAFKASETTINGS__BOOTSTRAPSERVERS}
      JwtSettings__SecretKey: ${JWTSETTINGS__SECRETKEY}
      JwtSettings__Issuer: ${JWTSETTINGS__ISSUER}
      JwtSettings__Audience: ${JWTSETTINGS__AUDIENCE}
      JwtSettings__ExpiresInMinutes: ${JWTSETTINGS__EXPIRESINMINUTES}
    ports:
      - "8080:8080"