services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: ghcr.io/${GITHUB_USERNAME}/productservice-migrate:latest
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: ${CONNECTIONSTRINGS__DEFAULTCONNECTION}

  api:
    image: ghcr.io/${GITHUB_USERNAME}/productservice-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    environment:
      ConnectionStrings__DefaultConnection: ${CONNECTIONSTRINGS__DEFAULTCONNECTION}
      ASPNETCORE_URLS: http://+:8081
      JwtSettings__SecretKey: ${JWTSETTINGS__SECRETKEY}
      JwtSettings__Issuer: ${JWTSETTINGS__ISSUER}
      JwtSettings__Audience: ${JWTSETTINGS__AUDIENCE}
      JwtSettings__ExpiresInMinutes: ${JWTSETTINGS__EXPIRESINMINUTES}
    ports:
      - "8081:8081"

volumes:
  pgdata:
