FROM mcr.microsoft.com/dotnet/sdk:9.0 AS migrate

WORKDIR /src

COPY . .

RUN dotnet restore ./ProductService.Data/ProductService.Data.csproj

RUN dotnet tool install --global dotnet-ef --version 9.0.7

ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "./ProductService.Data/ProductService.Data.csproj", "--startup-project", "./ProductService.Api/ProductService.Api.csproj"]