name: AuthService CI

on:
  push:
    paths:
      - 'backend/AuthService/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'backend/AuthService/**'
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    name: Build .NET Web API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Configure GitHub Packages NuGet source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "github" --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore AuthService.sln
        working-directory: backend/AuthService

      - name: Build solution
        run: dotnet build --no-restore --configuration Release AuthService.sln
        working-directory: backend/AuthService

      - name: Build Docker images with Docker Compose
        env:
          GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
          GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: docker compose -f backend/AuthService/AuthService.Api/docker-compose.yml build migrate api

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            backend/AuthService/**/bin/
            backend/AuthService/**/obj/

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: backend/AuthService/

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Configure GitHub Packages NuGet source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "github" --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore AuthService.sln
        working-directory: backend/AuthService

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release AuthService.sln
        working-directory: backend/AuthService