name: Frontend CI

on:
  push:
    paths:
      - "frontend/app/**"
    branches: [main]
  pull_request:
    paths:
      - "frontend/app/**"
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/app

      - name: Build React app
        run: npm run build
        working-directory: frontend/app
