name: Frontend CI

on:
  push:
    paths:
      - "frontend/app/**"
    branches: [main]
  pull_request:
    paths:
      - "frontend/app/**"
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/app

      - name: Build React app
        run: npm run build
        working-directory: frontend/app

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/app/dist

  deploy:
    name: Push Docker Image to GHCR
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/app/dist

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -f frontend/Dockerfile -t ghcr.io/${{ github.repository_owner }}/frontend:latest frontend/

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/frontend:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Sync dist folder to S3 bucket
        run: aws s3 sync frontend/app/dist/ s3://myminiecommercebucket/ --delete
