name: ProductService CI

on:
  push:
    paths:
      - 'backend/ProductService/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'backend/ProductService/**'
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    name: Build .NET Web API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ProductService.sln
        working-directory: backend/ProductService

      - name: Build solution
        run: dotnet build --no-restore --configuration Release ProductService.sln
        working-directory: backend/ProductService

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            backend/ProductService/**/bin/
            backend/ProductService/**/obj/

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: backend/ProductService/

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ProductService.sln
        working-directory: backend/ProductService

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release ProductService.sln
        working-directory: backend/ProductService